### ISSUE TITLE
Doesn't work with Chrome's emulation on desktop

### ISSUE THREAD

**Issue by greggman** [dorukeker/gyronorm.js#10]
Chrome has device orientation emulation in their DevTools

![chrome-device-orientation](https://cloud.githubusercontent.com/assets/234804/8352584/4d7f9c28-1b71-11e5-8656-e8e18675fc6f.gif)

But gyronorm fails the promise. I have no idea if there's a workaround or if this is a bug in Chrome itself that it's maybe not advertizing support? In any case it would be nice if there was a way to use gyronorm this way as it's really useful to debug.

**Comment by greggman** [comment]
Hmmm, I just noticed Chrome updated to 43.0.2357.130 (64-bit) on OSX and the behavior seems to have changed. Now I have the opposite problem which is the promise resolves when I'm in standard desktop mode with no orientation available when I'd prefer it reject :disappointed:

**Comment by greggman** [comment]
Ok, more ... I guess you're looking for some change in values which makes sense since the sensors usually jumble. So I found write after I start my app if I rotate the emulator within a second or so the promise resolves, if not it rejects. I guess that's fine as a workaround.

**Comment by dorukeker** [comment]
Hello,

Starting from v2.0.0, gyronorm is build up on FullTilt. So this is the same issue that was discussed here:
https://github.com/Full-Tilt/Full-Tilt/issues/7

I have updated gyronorm to use the latest version of FullTilt. The issue with the Chrome dev tools still remains (just like it is for FullTilt). However you can debug using [doe](https://github.com/richtr/doe).

Here you can see the gyronorm demo in doe
(https://dorukeker.github.io/gyronorm_on_doe)

Cheers,
Doruk

**Comment by dorukeker** [comment]
BTW the project with flowers and butterflies is very nice :+1:
