### ISSUE TITLE
There is no dependency setting on package.json 

### ISSUE THREAD

**Issue by happyhj** [dorukeker/gyronorm.js#22]
There is no dependency setting on package.json. 
And also there is no dependency on npm.

so I cannot install all dependencies (FULLTILT and ES6Promise) by "npm install gyronorm" command.

Can you add dependency setting?

**Comment by dorukeker** [comment]
A PR would be nice :)
FullTilt is not on NPM so I cannot add it to package.json as dependency. I suggest to use `$ bower install gyronorm`

In the `/dist` folder there are different builds. `/dist/gyronorm.complete.min.js` contains all the dependency libraries in one file. So if you use that one you don't need to add any other JS files to your project.

You need the dependencies added separately only if you use `/dist/gyronorm.js` or `/dist/gyronorm.min.js`

I hope this helps.
Cheers,
D.
