### ISSUE TITLE
ios alpha differs from android after screen timeout or after exiting and coming back to tab

### ISSUE THREAD

**Issue by jasan-s** [dorukeker/gyronorm.js#26]

**Comment by dorukeker** [comment]
Hello,

If you are using GAME-based orientation values you can do the following.
- Detect if the user is still using the page or not. I used this (https://github.com/serkanyersen/ifvisible.js) to detect it.
- when the user is back you can use the `setHeadDirection()` https://github.com/dorukeker/gyronorm.js/wiki/API-Documentaion#setheaddirection to reset the direction of the experience.

But I assume question is related with the scenario for your other topic. And that wont work for  WORLD-based orientation. And I addressed the problems with WORLD-based orientation in the other issue (https://github.com/dorukeker/gyronorm.js/issues/25)

Cheers,
Doruk
