### ISSUE TITLE
Usage with webpack

### ISSUE THREAD

**Issue by GabrielGil** [dorukeker/gyronorm.js#27]
Hello!

I am trying to use this library with webpack (ES6 import) however, something seems to be missing as the file imported is the main one specified in `package.json` which seems to not have all the needed dependencies.

Is any work on progress about this? Something I might help on?

Thank you!

**Comment by dorukeker** [comment]
Hello Gabriel,
I am not very knowledgeable about the ES6 imports. And there is no current work on this.
So if you can fix and send a PR I'd be more than glad to merge. :)

Cheers,
Doruk

**Comment by GabrielGil** [comment]
alright, I understand. I am currently experimenting with the library and it seems the major of the problems are the libraries.

I will be working on this definitely, so I would appreciate to keep this issue open because I am planning to send a PR at some point soon. 

Thank you!

**Comment by dorukeker** [comment]
Super. I will keep it open.
Cheers!

**Comment by GabrielGil** [comment]
Hi! Thank you for ping me on this. I have just tried it out on 2.0.5 and it seems that still not working right.

I have checked the PR as well, and that solutions seems not valid to me. I believe the error is in the export around [this line](https://github.com/dorukeker/gyronorm.js/blob/master/dist/gyronorm.complete.js#L1483).

The error I am getting is:

```
Uncaught TypeError: Cannot set property 'GyroNorm' of undefined
```

**Comment by GabrielGil** [comment]
I made it work with AMD and CommonJS finally. 😄 

I will make a PR tomorrow after some testing. I hope it helps, and thank you again for your attention.

**Comment by botraunak** [comment]
Still facing this issue. what version should we be getting where this would be solved? i'm using `"gyronorm": "^2.0.6",`

**Comment by GabrielGil** [comment]
Yes, I can confirm at version 2.0.6 the imports work just fine:

```js
// ES6+
import Gyronorm from 'gyronorm';
// Typescript
let Gyronorm = require('gyronorm');
let gs = new Gyronorm();
console.log('Gyronorm instance', gs);
```

**Comment by botraunak** [comment]
@GabrielGil  Thanks for the reply. npm was fetching 2.0.4 for unknown reasons.
Related: [https://github.com/dorukeker/gyronorm.js/issues/40#issuecomment-308603450](https://github.com/dorukeker/gyronorm.js/issues/40#issuecomment-308603450)
