### ISSUE TITLE
Uncaught TypeError: Cannot set property 'GyroNorm' of undefined

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [dorukeker/gyronorm.js#33]
webpack, strict  mode;
in strict mode this in functions is undefined!
you use (function(root){  code  })(this)
is not correct! you not correct detect root object!

need:
```javascript
var root = Function("return this")();
```
Function constructor stopping "strict mode" scope, and `this` link to global object.

![image](https://cloud.githubusercontent.com/assets/19378179/22940221/38ab86cc-f2f2-11e6-92bd-ca53948fe1ad.png)

**Comment by uMaxmaxmaximus** [comment]
oh, im wrong, 


https://monosnap.com/file/drOD9zSAnN3DhO7O9jO6LS5JFpqTJh.png
![image](https://cloud.githubusercontent.com/assets/19378179/22940429/e305f1c0-f2f2-11e6-831d-a3d5ebdcfbc3.png)

first anrument is not `this` is `undefined` =)))))

**Comment by GabrielGil** [comment]
hi! Glad to find out more people are using Gyronorm with webpack. I have changed the exporting on febcc79d39abf1468a6feefb19b4b03ffde59732, this has been released on 2.0.6, but @dorukeker didn't build it on the complete version.

This is why I believe this does not apply to the latest version. 

Please, let me know if I can be of any help. :)

**Comment by dorukeker** [comment]
Hi @GabrielGil 
I now see your PR was not included to the release.
I remade the release. It should be solved now.

Can you have a look and let me know if all works fine?

Cheers,
Doruk

**Comment by GabrielGil** [comment]
Yes, it is perfect now. I had actually mentioned in my pr (https://github.com/dorukeker/gyronorm.js/pull/30#issuecomment-275853161) that just needed the build and version number updates.

Thank you one more time @dorukeker
