### ISSUE TITLE
npm package outdated

### ISSUE THREAD

**Issue by siemiatj** [dorukeker/gyronorm.js#34]
Hey. Any chances to update package in npm to 2.0.6 ?

In the meantime if anyone needs the latest version just add the github url in packages.json : 

```
  "dependencies": {
    "gyronorm": "git://github.com/dorukeker/gyronorm.js.git#v2.0.6",
```

it will show that 2.0.5 was installed, but it uses the latest commit ;)

**Comment by dorukeker** [comment]
@siemiatj I made a new release via GitHub 2.0.6. Also updated my package.json to show the new version. But I see NPM still shows the older version number.

This used to go automatically. Any suggestion? Am I missing anything here?

**Comment by dorukeker** [comment]
Never mind. I figured it out here https://docs.npmjs.com/getting-started/publishing-npm-packages
I close the issue. Pleas re-open if you think it is solved.
Cheers,
Doruk
