### ISSUE TITLE
Error in readme (2.0.6, NPM)

### ISSUE THREAD

**Issue by mode777** [dorukeker/gyronorm.js#41]
I installed 2.0.6 via npm. 

Readme says:
`var GyroNorm = require('gyronorm').GyroNorm;`
This is actually undefined. What it should say is:
`var GyroNorm = require('gyronorm');`

Tested with Node 7.9.0

I don't know if this is a bug, because it is quite unusual to directly export the constructor

**Comment by dorukeker** [comment]
@mode777 I am not very familiar using AMD / CommonJS. So I take your word and update it :)
